const quotes = [
    "\"Act as if what you do makes a difference. It does.\" *William James*",
 "\"Good, better, best.  Never let it rest.  \'Til your good is better and your better is best.\" *St. Jerome*",
 "\"The secret of getting ahead is getting started.\" *Mark Twain*",
"\"Optimism is the faith that leads to achievement.  Nothing can be done without hope and confidence.\" *Helen Keller*",
"\"Only I can change my life.  No one can do it for me.\" *Carol Burnett*",
"\"Life is 10% what happens to you and 90% how you react to it.\" *Charles R. Swindoll*",
"\"I know where I\'m going and I know the truth, and I don\'t have to be what you want me to be.  I\'m free to be what I want.\" *Muhammad Ali*",
"\"Be thankful for what you have, you\'ll end up having more.  If you concentrate on what you don\'t have, you will never, ever have enough.\" *Oprah Winfrey*",
"\"Be kind whenever possible.  It is always possible.\" *Dalai Lama*",
"\"If you fell down yesterday, stand up today.\" *H.G. Wells*",
"\"If you\'re going through hell, keep going.\" *Winston Churchill*",
"\"Be miserable.  Or motivate yourself.  Whatever has to be done, it\'s always your choice.\" *Wayne Dyer*",
"\"If you can dream it, you can do it.\" *Walt Disney*",
"\"Always do your best.  What you plant now, you will harvest later.\" *Og Mandino*",
"\"Our greatest weakness lies in giving up.  The most certain way to succeed is always to try just one more time.\" *Thomas A. Edison*",
"\"You are never too old to set another goal or to dream a new dream.\" *Les Brown*",
"\"When you reach the end of your rope, tie a knot in it and hang on.\" *Franklin D. Roosevelt*",
"\"Either you run the day, or the day runs you.\" *Jim Rohn*",
"\"To begin, begin.\" *William Wordsworth*",
"\"What you do today can improve all your tomorrows.\" *Ralph Marston*",
"\"Try to be a rainbow in someone\'s cloud.\" *Maya Angelou*",
"\"Two roads diverged in a wood and...I took the one less traveled by, and that has made all the difference.\" *Robert Frost*",
"\"Nothing is impossible, the word itself says \'I\'m possible!\'\" *Audrey Hepburn*",
"\"As we express our gratitiude, we must never forget that the highest appreciation is not to utter words, but to live by them.\" *John F. Kennedy*",
"\"The power of imagination makes us infinite.\" *John Muir*",
"\"If opportunity doesn\'t knock, build a door.\" *Milton Berle*",
"\"No act of kindness, no matter how small, is ever wasted.\" *Aesop*",
"\"Someone is sitting in the shade today because someone planted a tree a long time ago.\" *Warren Buffett*",
"\"All you need is the plan, the road map, and the courage to press on to your destination.\" *Earl Nightingale*",
"\"Your present circumstances don\'t determine where you can go; they merely determine where you start.\" *Nido Qubein*",
"\"Each day provides its own gifts.\" *Marcus Aurelius*",
"\"With self-discipline most anything is possible.\" *Theodore Roosevelt*",
"\"I believe every human has a finite number of heartbeats.  I don\'t intend to waste any of mine.\" *Neil Armstrong*",
"\"I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination.\" *Jimmy Dean*",
"\"I\'ve been absolutely terrified every moment of my life; and I\'ve never let it keep me from doing a single thing I wanted to do.\" *Georgia O\'Keeffe*",
"\"Put your heart, mind, and soul into even your smallest acts. This is the secret of success.\" *Swami Sivananda*",
"\"Your heart is full of fertile seeds, waiting to sprout.\" *Morihei Ueshiba*",
"\"Just don\'t give up trying to do what you really want to do. Where there is love and inspiration, I don'\t think you can go wrong.\" *Ella Fitzgerald*",
"\"If you believe in yourself and have dedication and pride, and never quit, you\'ll be a winner. The price of victory is high but so are the rewards.\" *Bear Bryant*",
"\"You change your life by changing your heart.\" *Max Lucado*",
"\"Reach for it.  Push yourself as far as you can.\" *Christa McAuliffe*",
"\"Today I choose life. Every morning when I wake up I can choose joy, happiness, negativity, pain...To feel the freedom that comes from being able to continue to make mistakes and choices - today I choose to feel life, not to deny my humanity but embrace it.\" *Kevyn Aucoin*",
"\"Our time here is magic! It\'s the only space you have to realize whatever it is that is beautiful, whatever is true, whatever is great, whatever is potential, whatever is rare, whatever is unique, in.  It\'s the only space.\" *Ben Okri*",
"\"I am not afraid of tomorrow, for I have seen yesterday and I love today!\" *William Allen White*",
"\"I have decided to stick with love. Hate is too great a burden to bear.\" *Martin Luther King, Jr.*",
"\"Open your eyes, look within.  Are you satisfied with the life you\'re living?\" *Bob Marley*",
"\"A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.\" *George Bernard Shaw*",
"\"If you love life, don\'t waste time, for time is what life is made up of.\" *Bruce Lee*",
"\"The shoe that fits one person pinches another; there is no recipe for living that suits all cases.\" *Carl Jung*",
"\"If life were predictable it would cease to be life, and be without flavor.\" *Eleanor Roosevelt*",
"\"We are all here for a spell, get all the good laughs you can.\" *Will Rogers*",
"\"That it will never come again is what makes life sweet.\" *Emily Dickinson*",
"\"The privilege of a lifetime is being who you are.\" *Joseph Campbell*",
"\"Seventy percent of success in life is showing up.\" *Woody Allen*",
"\"When I started counting my blessings, my whole life turned around.\" *Willie Nelson*",
"\"When you are grateful - when you can see what you have - you unlock blessings to flow in your life.\" *Suze Orman*",
"\"Success is not a good teacher, failure makes you humble.\" *Shah Rukh Khan*",
"\"I\'ve failed over and over and over again in my life and that is why I succeed.\" *Michael Jordan*",
"\"The ladder of success is best climbed by stepping on the rungs of opportunity.\" *Ayn Rand*",
"\"The successful man will profit from his mistakes and try again in a different way.\" *Dale Carnegie*",
"\"Success is blocked by concentrating on it and planning for it...Success is shy - it won\'t come out while you\'re watching.\" *Tennessee Williams*",
"\"If you wish to succeed in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother, and hope your guardian genius.\" *Joseph Addison*",
"\"Find something you\'re passionate about and keep tremendously interested in it.\" *Julia Child*",
"\"Success is falling nine times and getting up ten.\" *Jon Bon Jovi*",
"\"Most people give up just when they\'re about to achieve success. They quit on the one yeard line. They give up at the last minute of the game one foot from a winning touchdown.\" *Ross Perot*",
"\"Frustration, although quite painful at times, is a very positive and essential part of success.\" *Bo Bennett*",
"\"Don\'t aim for success if you want it; just do what you love and believe in, and it will come naturally.\" *David Frost*",
"\"Success has a simple formula: do your best, and people may like it.\" *Sam Ewing*",
"\"One cool judgment is worth a thousand hasty counsels.  The thing to do is to supply light and not heat.\" *Woodrow Wilson*",
"\"Competition is great. And as long as it\'s friendly and not a malicious thing, then I think it\'s cool.\" *Janet Jackson*",
"\"If you set goals and go after them with all the determination you can muster, your gifts will take you places that will amaze you.\" *Les Brown*",
"\"The thing that is really hard, and really amazing, is giving up on being perfect and beginning the work of becoming yourself.\" *Anna Quindlen*",
"\"Nobody in life gets exactly what they thought they were going to get. But if you work really hard and you\'re kind, amazing things will happen.\" *Conan O\'Brien*",
"\"When you have confidence, you can have a lot of fun. And when you have fun, you can do amazing things.\" *Joe Namath*",
"\"It\'s amazing how much you can learn if your intentions are truly earnest.\" *Chuck Berry*",
"\"Listen once in a while. It\'s amazing what you can hear.\" *Russell Baker*",
"\"If you dream of something worth doing and then simply go to work on it and don\'t think anything of personalities, or emotional conflicts, or of money, or of family distractions, it is amazing how quickly you get through those 5,000 steps.\" *Edwin Land*",
"\" When you\'re true to who you are, amazing things happen.\" *Deborah Norville*",
"\"Between two evils, I always pick the one I never tried before.\" *Mae West*",
"\"Do not take life too seriously.  You will never get out of it alive.\" *Elbert Hubbard*",
"\"Be happy for this moment. This moment is your life.\" *Omar Khayyam*",
"\"Don\'t wait around for other people to be happy for you. Any happiness you get you\'ve got to make yourself.\" *Alice Walker*",
"\"A sure way to lose happiness, I found, is to want it at the expense of everything else.\" *Bette Davis*",
"\"Happiness often sneaks in through a door you didn\'t know you left open.\" *John Barrymore*",
"\"Try to make at least one person happy every day. If you cannot do a kind deed, speak a kind word. If you cannot speak a kind word, think a kind thought. Count up, if you can, the treasure of happiness that you would dispense in a week, in a year, in a lifetime!\" *Lawrence G Lovasik*",
"\"Every day is a new day, and you\'ll never be able to find happiness if you don\'t move on.\" *Carrie Underwood*",
"\"I think most of us are raised with preconceived notions of the choices we\'re supposed to make. We waste so much time making decisions based on someone else\'s idea of our happiness; what will make you a good citizen or a good wife or daughter or actress. Nobody says, \'Just be happy; go be a cobbler or go live with goats.\'\" *Sandra Bullock*",
"\"See to do good, and you will find that happiness will run after you.\" *James Freeman Clarke*",
"\"Don\'t ever doubt yourselves or waste a second of your life. It\'s too short, and you\'re too special.\" *Ariana Grande*",
"\"I may be a senior, but so what? I\'m still hot.\" *Betty White*",
"\"My recipe for life is not being afraid of myself, afraid of what I think or of my opinions.\" *Eartha Kitt*",
"\"I\'m selfish, impatient, and a little insecure. I make mistakes, I\'m out of control, and at times hard to handle. But if you can\'t handle me at my worst, then you sure as hell don\'t deserve me at my best.\" *Marilyn Monroe*",
"\"I don\'t think about my titles and roles; I just do what feels right.\" *Meghan Markle*",
"\"Everyone looks to an artist for something more than just the music, and that message of being comfortable in my own skin is number one for me.\" *Lizzo*",
"\"I believe it\'s time that women truly owned their superpowers and used their beauty and strength to change the world around them.\" *Janelle Monae*",
"\"Sometimes when we are generous in small, barely detectable ways, it can change someone else\'s life forever.\" *Margaret Cho*",
"\"You can\'t juggle it all 100 percent. You don\'t have to be perfect. You don\'t have to do everything.\" *Connie Chung*",
"\"What we find is that if you have a goal that is very, very far out, and you approach it in little steps, you start to get there faster. Your mind opens up to the possibilities.\" *Mae Jemison*",
"\"You are not a problem that needs solving.\" *Eckhart Tolle*",
"\"Aging is not lost youth but a new stage of opportunity and strength.\" *Betty Friedan*",
"\"The excursion is the same when you go looking for your sorrow as when you go looking for your joy.\" *Eudora Welty*",
"\"One may walk over the highest mountain one step at a time.\" *Barbara Walters*",
"\"I am where I am because I believe in all possibilities.\" *Whoopi Goldberg*",
"\"You will never do anything in this world without courage. It is the greatest quality of the mind next to honor.\" *Aristotle*"
]

const newQuote = () => {
    let randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('famousQuote').innerHTML = quotes[randomNumber];
}